import React from 'react';

export default function AboutPage() {
  return (
    <main className="min-h-screen py-16 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold text-slate-100 mb-8">About SanskritAI</h1>
      
      <div className="space-y-12 text-slate-300 leading-relaxed">
        <section>
          <h2 className="text-2xl font-semibold text-amber-500 mb-4">The Problem</h2>
          <p>
            Sanskrit is a highly inflected, classical language with complex morphology, rich compounding rules (Samāsa), and dynamic sound changes (Sandhi). These characteristics make direct word-for-word translation incredibly challenging. Traditional rule-based parsers often struggle with ambiguity, while generic LLMs may hallucinate grammatical features.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-amber-500 mb-4">The Solution</h2>
          <p>
            SanskritAI combines Natural Language Processing (NLP) techniques and modern Transformer-based language models to not only translate Sanskrit sentences into English, but also to explain their underlying linguistic structure. By breaking down the grammatical roles, identifying roots, and decoding Sandhi, we provide an academic-grade tool designed for students and scholars alike.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-amber-500 mb-4">Technologies Used</h2>
          <ul className="grid grid-cols-2 gap-4 mt-4 text-sm font-medium">
            <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"/> Natural Language Processing</li>
            <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"/> Transformer Models</li>
            <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"/> Morphological Analysis</li>
            <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"/> Next.js & React</li>
            <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"/> TypeScript & Tailwind CSS</li>
            <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"/> Python & FastAPI (Backend)</li>
            <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"/> PyTorch & Hugging Face</li>
          </ul>
        </section>

        <div className="bg-amber-950/30 border border-amber-900/50 p-4 rounded-xl mt-8">
          <p className="text-amber-200/80 text-sm">
            <strong>Note:</strong> Advanced grammatical analysis generated by AI may be probabilistic. While our models strive for high accuracy, complex Sandhi splits and ambiguous word forms should be cross-referenced with traditional commentaries (Bhashyas) for strict scholarly use.
          </p>
        </div>
      </div>
    </main>
  );
}
